import type { TerminologyEntry } from "./terminology";

type Category = "Strategy" | "Finance" | "Sales" | "Product" | "Operations" | "Partnerships" | "People";

const businessTerm = (
  term: string,
  category: Category,
  meaning: string,
  why: string,
  questions: [string, string, string],
  aliases: string[] = [],
  triggers: string[] = [],
): TerminologyEntry => ({
  term,
  category,
  meaning,
  why,
  question: questions[0],
  moreQuestions: questions.slice(1),
  aliases,
  triggers,
  source: "local",
});

export const businessTerminology: TerminologyEntry[] = [
  // Strategy — 8 terms
  businessTerm("Business model", "Strategy", "How a company creates value for customers and earns money from it.", "They may be explaining how the company operates, charges customers or plans to grow.", ["So where does most of the revenue come from?", "What part of the business model is hardest to scale?", "Has the business model changed as the company has grown?"], [], ["how we make money", "revenue model"]),
  businessTerm("Value proposition", "Strategy", "The clear reason a customer should choose a product or service over the alternatives.", "They may be describing the customer problem they solve and what makes the offer compelling.", ["Which part of the value proposition matters most to customers?", "How do customers describe the value in their own words?", "What usually convinces a customer to choose you?"], [], ["customer value", "why customers choose us"]),
  businessTerm("Competitive advantage", "Strategy", "A strength that helps a company perform better than competitors and is difficult to copy.", "They may be discussing differentiation, defensibility or why the business can keep winning.", ["What makes that difficult for competitors to copy?", "Is that advantage getting stronger over time?", "What do customers notice most about the difference?"], ["competitive edge"], ["differentiator", "defensible advantage"]),
  businessTerm("Go-to-market strategy", "Strategy", "The plan for reaching target customers, selling the product and supporting adoption.", "They may be discussing channels, positioning, sales motion or a product launch.", ["Which go-to-market channel is working best right now?", "What has been hardest about reaching the right customers?", "Has the go-to-market approach changed since launch?"], ["GTM", "go to market"], ["market entry strategy", "sales motion"]),
  businessTerm("Product-market fit", "Strategy", "Evidence that a product solves an important problem for a market that strongly wants it.", "They may be assessing whether customer demand is repeatable and strong enough to support growth.", ["What signals tell you that product-market fit is getting stronger?", "Which customer group feels the problem most urgently?", "What still needs to improve before demand feels repeatable?"], ["PMF", "product market fit"], ["market fit"]),
  businessTerm("Total addressable market", "Strategy", "The total possible demand if a product could serve every relevant customer in its market.", "They may be estimating the scale of an opportunity for strategy, fundraising or planning.", ["What assumptions have the biggest effect on the market estimate?", "Which part of the total market is most realistic to pursue first?", "Is the market itself growing or mainly shifting between providers?"], ["TAM"], ["total market opportunity"]),
  businessTerm("Serviceable available market", "Strategy", "The part of the total market a company can serve with its current product and reach.", "They may be narrowing a broad market estimate to the customers they can realistically support.", ["Which customers are inside the serviceable market today?", "What currently keeps the rest of the market out of reach?", "Could the serviceable market expand with a new product or region?"], ["SAM"], ["serviceable market"]),
  businessTerm("Business case", "Strategy", "A structured explanation of why an initiative is worth doing, including value, cost and risk.", "They may need approval, budget or stakeholder support before a project can proceed.", ["What evidence matters most in the business case?", "Who needs to be convinced before it moves forward?", "Which benefit is hardest to quantify?"], [], ["investment case", "case for investment"]),

  // Finance — 10 terms
  businessTerm("Annual recurring revenue", "Finance", "The recurring subscription revenue a business expects over a year.", "They may be describing the scale and predictability of a subscription business.", ["What is driving most of the ARR growth?", "How much of the annual recurring revenue comes from existing customers?", "Is growth coming more from new customers or expansion?"], ["ARR"], ["yearly recurring revenue"]),
  businessTerm("Monthly recurring revenue", "Finance", "The recurring subscription revenue a business expects each month.", "They may be monitoring short-term growth and the stability of subscription income.", ["What changed the monthly recurring revenue most recently?", "How predictable is MRR from one month to the next?", "Which customer segment contributes most to it?"], ["MRR"], ["monthly subscription revenue"]),
  businessTerm("Gross margin", "Finance", "Revenue left after subtracting the direct cost of delivering the product or service.", "They may be assessing whether growth becomes more profitable as the business scales.", ["What has the biggest effect on gross margin?", "Does the margin improve as volume increases?", "Which part of delivery is most expensive today?"], [], ["gross profit margin"]),
  businessTerm("Cash flow", "Finance", "The movement of cash into and out of a business over time.", "They may be discussing whether the company can fund operations and investments when payments arrive at different times.", ["What creates the most pressure on cash flow?", "Are payment terms a major factor?", "How predictable is cash flow across the year?"], [], ["cash position", "working capital"]),
  businessTerm("Burn rate", "Finance", "The amount of cash a company spends beyond what it earns during a period.", "They may be discussing spending discipline and how quickly available funding is being used.", ["What is driving the burn rate at the moment?", "Which costs are easiest to adjust if needed?", "Has the burn rate changed as the team has grown?"], [], ["cash burn"]),
  businessTerm("Runway", "Finance", "How long a company can continue operating before it needs more cash or becomes self-sustaining.", "They may be evaluating fundraising timing, spending plans or financial risk.", ["What assumptions are built into the runway estimate?", "What would extend the runway most effectively?", "When would the team need to make a funding decision?"], ["cash runway"], ["months of runway"]),
  businessTerm("Break-even", "Finance", "The point where total revenue covers total costs and the business is no longer losing money.", "They may be discussing profitability targets or how much scale is needed for sustainability.", ["What needs to change to reach break-even?", "Is the target mainly dependent on growth or lower costs?", "How sensitive is the timeline to customer demand?"], ["breakeven", "break even"], ["break-even point"]),
  businessTerm("Return on investment", "Finance", "A comparison between the value gained from an investment and what it cost.", "They may need to show that a project produces enough measurable benefit to justify funding.", ["Which benefits are included in the ROI calculation?", "How long does it usually take to see a return?", "What would make the investment clearly worthwhile?"], ["ROI"], ["investment return"]),
  businessTerm("EBITDA", "Finance", "A measure of operating performance before interest, taxes, depreciation and amortisation.", "They may be comparing the underlying performance of businesses or tracking profitability before financing and accounting effects.", ["What is having the biggest impact on EBITDA?", "Is the improvement coming from growth or efficiency?", "How does management use EBITDA in decisions?"], ["earnings before interest taxes depreciation and amortisation"], ["operating earnings"]),
  businessTerm("Unit economics", "Finance", "The revenue and direct costs associated with one customer, sale or unit of activity.", "They may be checking whether growth creates value at the level of each customer or transaction.", ["Which unit matters most for understanding the economics?", "At what point does a customer become profitable?", "How have the unit economics changed with scale?"], [], ["economics per customer", "per-customer economics"]),

  // Sales — 10 terms
  businessTerm("Ideal customer profile", "Sales", "A description of the type of customer most likely to benefit from and buy the product.", "They may be focusing sales and marketing on the accounts with the strongest fit.", ["What makes a customer a particularly strong fit?", "Has the ideal customer profile changed over time?", "Which signals help the team identify those customers early?"], ["ICP"], ["ideal client profile", "target customer profile"]),
  businessTerm("Customer acquisition cost", "Sales", "The average sales and marketing cost required to gain a new customer.", "They may be assessing whether customer growth is efficient and sustainable.", ["Which channel has the lowest acquisition cost?", "What is pushing CAC up or down?", "How quickly is that cost recovered after a customer signs?"], ["CAC"], ["cost to acquire a customer", "acquisition cost"]),
  businessTerm("Customer lifetime value", "Sales", "The expected value a customer contributes throughout their relationship with the business.", "They may be comparing long-term customer value with the cost of acquiring and serving them.", ["What has the biggest influence on lifetime value?", "Which customer segment tends to stay longest?", "How do you increase value without creating a poor customer experience?"], ["LTV", "CLV"], ["lifetime customer value"]),
  businessTerm("Sales pipeline", "Sales", "The active sales opportunities moving through the steps toward a possible deal.", "They may be discussing future revenue, deal quality or where prospects get stuck.", ["Where do opportunities most often stall in the pipeline?", "How confident are you in the current pipeline?", "Which stage needs the most attention right now?"], [], ["deal pipeline", "sales funnel"]),
  businessTerm("Conversion rate", "Sales", "The percentage of people or opportunities that complete a desired next step.", "They may be measuring how effectively interest turns into leads, customers or completed actions.", ["Which step has the biggest drop in conversion?", "What has improved the conversion rate most?", "Does conversion vary significantly by customer segment?"], [], ["conversion percentage", "close rate"]),
  businessTerm("Sales cycle", "Sales", "The time and stages involved in moving from initial interest to a completed sale.", "They may be explaining how long buying takes and which approvals or conversations slow it down.", ["Which part of the sales cycle takes longest?", "What usually helps a deal move faster?", "Does the cycle differ much between customer types?"], [], ["buying cycle", "deal cycle"]),
  businessTerm("Average contract value", "Sales", "The average monetary value of a customer contract over a defined period.", "They may be comparing deal sizes and deciding which customer segments to prioritise.", ["What is changing the average contract value?", "Are larger contracts also taking longer to close?", "Which customer segment has the strongest contract value?"], ["ACV"], ["average deal value", "average contract size"]),
  businessTerm("Churn", "Sales", "The rate at which customers or recurring revenue are lost over time.", "They may be discussing customer dissatisfaction, retention risk or the durability of revenue.", ["What are the most common reasons customers churn?", "Can the team usually see churn risk early?", "Which changes have improved retention most?"], ["customer churn", "revenue churn"], ["customers leaving", "customer loss rate"]),
  businessTerm("Retention", "Sales", "The ability to keep customers active and continuing to buy over time.", "They may be measuring customer satisfaction, product value and recurring revenue quality.", ["What keeps customers engaged for the long term?", "When is retention risk usually highest?", "Which customer behaviours predict strong retention?"], ["customer retention"], ["renewal rate", "customers staying"]),
  businessTerm("Procurement", "Sales", "The process an organisation uses to evaluate, approve and purchase products or services.", "They may be describing the commercial, legal and security steps required before a deal can close.", ["Which procurement step tends to take longest?", "Who normally owns the process on the client side?", "What information helps procurement move faster?"], ["purchasing process"], ["vendor approval", "procurement cycle"]),

  // Product — 8 terms
  businessTerm("Minimum viable product", "Product", "The simplest product version that can test the main value with real users.", "They may be trying to learn quickly before committing to a larger build.", ["What is the main assumption the MVP needs to test?", "What did early users respond to most strongly?", "What was deliberately left out of the first version?"], ["MVP"], ["minimum viable version"]),
  businessTerm("Product roadmap", "Product", "A directional plan showing product priorities and expected development over time.", "They may be discussing sequencing, commitments or how customer needs shape future work.", ["What has the biggest influence on the roadmap?", "How often do priorities change?", "Which roadmap item has the most uncertainty?"], ["roadmap"], ["product plan"]),
  businessTerm("Use case", "Product", "A specific situation in which someone uses a product to achieve an outcome.", "They may be making an abstract product more concrete by describing who uses it and why.", ["Which use case creates the clearest value?", "Who experiences that problem most often?", "Are customers using it in ways you did not expect?"], ["use-case"], ["customer scenario"]),
  businessTerm("User journey", "Product", "The sequence of steps and experiences someone has while trying to achieve a goal with a product or service.", "They may be identifying friction, handoffs or opportunities to improve the experience.", ["Where is the most friction in the user journey?", "Which step matters most to the overall experience?", "How do you learn where users are getting stuck?"], ["customer journey"], ["user flow", "customer experience journey"]),
  businessTerm("Adoption", "Product", "The extent to which intended users begin using a product and make it part of their normal work.", "They may be discussing whether a launch or implementation is producing real behaviour change.", ["What is the biggest barrier to adoption?", "Which users adopt it fastest?", "How do you know it has become part of the normal workflow?"], ["product adoption", "user adoption"], ["adoption rate"]),
  businessTerm("Activation", "Product", "The point at which a new user first experiences the product’s intended value.", "They may be measuring whether onboarding successfully moves people into meaningful use.", ["What action tells you a user is activated?", "Where do users drop off before activation?", "What has improved time to value most?"], ["user activation"], ["activation rate", "time to value"]),
  businessTerm("Net Promoter Score", "Product", "A customer feedback measure based on how likely someone is to recommend a company or product.", "They may be using a simple loyalty signal to track customer sentiment over time.", ["What tends to move the NPS score most?", "How do you follow up on the reasons behind the score?", "Does the score differ much between customer groups?"], ["NPS"], ["promoter score"]),
  businessTerm("Proof of concept", "Product", "A limited test used to show that an idea or solution can work in a real setting.", "They may be reducing technical or business uncertainty before a larger commitment.", ["What does the proof of concept need to prove?", "Who decides whether the result is strong enough to continue?", "What happens if the test succeeds?"], ["POC", "proof-of-concept"], ["pilot test", "concept validation"]),

  // Operations — 8 terms
  businessTerm("Key performance indicator", "Operations", "A measurable signal used to track progress on an important business outcome.", "They may be defining how success is monitored and where management focuses attention.", ["Which KPI best reflects the real outcome?", "How often does the team review it?", "What action changes when the indicator moves?"], ["KPI", "key performance indicators"], ["performance metric"]),
  businessTerm("Objectives and key results", "Operations", "A goal-setting method that pairs a clear objective with measurable results.", "They may be aligning teams around priorities and defining what progress should look like.", ["Which key result is hardest to influence?", "How are the OKRs connected across teams?", "What happens when priorities change during the cycle?"], ["OKR", "OKRs"], ["objective and key results"]),
  businessTerm("Request for proposal", "Operations", "A formal invitation asking vendors to propose how they would meet a defined need.", "They may be describing a structured buying process used to compare suppliers.", ["What matters most in the proposal evaluation?", "How much room is there to shape the solution?", "Who makes the final decision after the RFP?"], ["RFP"], ["tender process", "vendor proposal request"]),
  businessTerm("Stakeholder", "Operations", "A person or group affected by, responsible for or able to influence an initiative.", "They may be mapping who needs to be involved, informed or aligned for progress.", ["Which stakeholder has the strongest influence on the outcome?", "Where is alignment still missing?", "Who will feel the change most directly?"], ["stakeholders"], ["stakeholder alignment", "stakeholder management"]),
  businessTerm("Governance", "Operations", "The rules, roles and decision processes used to direct and control work.", "They may be discussing who has authority, how decisions are reviewed and how accountability is maintained.", ["Who owns the key governance decisions?", "Where does governance slow the work down?", "Which decisions need a formal review?"], ["corporate governance"], ["governance model", "decision governance"]),
  businessTerm("Compliance", "Operations", "The work required to follow relevant laws, regulations, standards and internal policies.", "They may be identifying requirements that shape how a product or process must operate.", ["Which compliance requirement has the biggest practical impact?", "Who is responsible for signing off?", "Does compliance need to be designed in from the start?"], ["regulatory compliance"], ["compliance requirement", "regulatory requirement"]),
  businessTerm("Change management", "Operations", "A structured approach for helping people and organisations adopt a new way of working.", "They may be addressing communication, training, resistance and behavioural change around an initiative.", ["Where do you expect the most resistance to change?", "Who needs to support the change visibly?", "How will you know the new behaviour has taken hold?"], [], ["organisational change", "change adoption"]),
  businessTerm("Scalability", "Operations", "The ability of a product, process or organisation to handle growth without breaking down or becoming disproportionately expensive.", "They may be considering whether the current approach can support more users, customers or volume.", ["What becomes difficult first as volume grows?", "Which part of the operation is least scalable today?", "How much growth can the current setup support?"], ["scalable"], ["scale the business", "scale operations"]),

  // Partnerships — 4 terms
  businessTerm("Strategic partnership", "Partnerships", "A collaboration where organisations combine complementary strengths to pursue shared long-term value.", "They may be exploring access to customers, capabilities, markets or credibility that would be difficult to build alone.", ["What would make the partnership valuable for both sides?", "Which capability does each partner bring?", "How would you measure whether the partnership is working?"], ["strategic alliance"], ["business partnership"]),
  businessTerm("Channel partner", "Partnerships", "An external company that helps market, sell, implement or support another company’s offering.", "They may be discussing how to reach customers through an established distribution or service network.", ["What role does the channel partner play after the sale?", "How are partners motivated to prioritise the product?", "Which customers are best reached through the channel?"], ["sales channel partner"], ["distribution partner", "partner channel"]),
  businessTerm("Revenue share", "Partnerships", "An arrangement where participating organisations divide revenue according to an agreed formula.", "They may be negotiating incentives and how value created together should be distributed.", ["How is the revenue share calculated?", "What behaviour is the arrangement meant to encourage?", "How do both sides handle revenue attribution?"], ["revenue-sharing"], ["share of revenue"]),
  businessTerm("Co-selling", "Partnerships", "A sales approach where two organisations work together to identify, develop and close opportunities.", "They may be coordinating account access, expertise and commercial responsibilities between partners.", ["Who owns the customer relationship during a co-sell?", "How are opportunities shared between the teams?", "What makes a co-selling motion work well?"], ["co selling", "joint selling"], ["sell together"]),

  // People — 2 terms
  businessTerm("Headcount", "People", "The number of people employed by an organisation or team.", "They may be discussing hiring plans, cost, capacity or organisational growth.", ["Which roles are the highest priority to add?", "Is headcount limited more by budget or available talent?", "How does the hiring plan connect to the company’s goals?"], ["employee count"], ["team size", "hiring plan"]),
  businessTerm("Cross-functional team", "People", "A team made up of people from different disciplines working toward a shared outcome.", "They may be explaining how work crosses boundaries between product, sales, operations or technical groups.", ["Which functions need to be represented for this to work?", "Where do handoffs between the teams become difficult?", "Who makes the final call when priorities conflict?"], ["cross functional team", "cross-functional collaboration"], ["multidisciplinary team"]),
];
